### ISSUE TITLE
`.site-content__theme`-ning `font-weight` qiymati pikselda berilgan

### ISSUE THREAD

**Issue by darxanov** [lazizbek0211/lazizbek0211-skilled#2]
https://github.com/lazizbek0211/lazizbek0211-skilled/blob/2c5b1f6097e803ae47a71aab81363a242d31cc0e/styles.css/styles.css#L111

Font-weight hossasiga qiymatni pikselda berilmasligi kerak :)

**Comment by lazizbek0211** [comment]
rahmat to`g`irlandi.hato ketib qolipti
