### ISSUE TITLE
Containerning o'lchamlari xato berilgan

### ISSUE THREAD

**Issue by IbragimovOlimjon** [lazizbek0211/lazizbek0211-skilled#8]
![image](https://user-images.githubusercontent.com/98340831/169809211-d3940cc7-aa81-4dc2-b51e-68a8fbca485c.png)

**Comment by lazizbek0211** [comment]
togri turiptiku containerning olchami1110px ku ikki chekkadan 30px paddingi bolsa 1170px boladiku
